%getFPCtable

% tabulate the Drag Lift and Dp for various cases


resultsNamesTN={'testFPC','testFPCP2','testFPCP4'};
resultsNamesWABE={'testFPCWABE','testFPCWABEP2','testFPCWABEP4'};

cdmaxRef=2.950921575;tcdmaxRef=3.93625;clmaxRef=0.47795;tclmaxRef=5.693125;dppRef=-0.1116;

fid=fopen('FPCDragLiftTable.tex','w');
fprintf(fid,'%% %s\n',datestr(now));
fprintf(fid,'%% this tex file was generated by getFPCtable.m\n\n');
fprintf(fid,'\\begin{figure}[h] \n\\begin{center}');
fprintf(fid,'\n\\begin{tabular}{rccccc} \\hline \n');
fprintf(fid,'\\hline \n');
%fprintf(fid,' \\multicolumn{6}{c}{ TN boundary conditions}   \\\\ \\hline\\hline\n');
fprintf(fid,' & $C_{d,\\max} $ & $ t(C_{d,\\max}) $ & $ C_{l,\\max} $ & $ t(C_{l,\\max}) $ & $ \\Delta p(8) $ \\\\ \\hline \n');

resultsNames=resultsNamesTN;
for i=1:length(resultsNamesTN)
    resultsName=resultsNames{i};
    run(sprintf('%s/maxcdclFile.m',resultsName));
    run(sprintf('%s/dpFile.m',resultsName));
    fprintf(fid,'TN  $\\mathbb{P}_%d $ & $%.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ \\\\ \\hline \n',2^(i-1),cdmax,tcdmax,clmax,tclmax,dp(end));
    fprintf('RE %14s: [%.2f%%,%.2f%%,%.2f%%]\n\n',resultsName,abs(cdmax-cdmaxRef)/cdmaxRef*100,abs(clmax-clmaxRef)/clmaxRef*100,abs(dp(end)-dppRef)/abs(dppRef)*100);
end

%fprintf(fid,'\\hline \n');
%fprintf(fid,' \\multicolumn{6}{c}{WABE boundary conditions}   \\\\ \\hline\\hline\n');
resultsNames=resultsNamesWABE;
for i=1:length(resultsNamesWABE)
    resultsName=resultsNames{i};
    run(sprintf('%s/maxcdclFile.m',resultsName));
    run(sprintf('%s/dpFile.m',resultsName));
    fprintf(fid,'WABE $\\mathbb{P}_%d $ & $%.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ \\\\ \\hline \n',2^(i-1),cdmax,tcdmax,clmax,tclmax,dp(end));
    fprintf('RE %14s: [%.2f%%,%.2f%%,%.2f%%]\n\n',resultsName,abs(cdmax-cdmaxRef)/cdmaxRef*100,abs(clmax-clmaxRef)/clmaxRef*100,abs(dp(end)-dppRef)/abs(dppRef)*100);
end


fprintf(fid,'\\hline \n');
fprintf(fid,' \\multicolumn{6}{c}{ Reference Values}   \\\\ \\hline\\hline\n');
refName='V. John \cite{John04}';
cdmax=2.950921575;tcdmax=3.93625;clmax=0.47795;tclmax=5.693125;dpp=-0.1116;
fprintf(fid,'%s & $%.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ \\\\ \\hline \n',refName,cdmax,tcdmax,clmax,tclmax,dpp);
refName='Liu {\em et al.} \cite{LiuLiuPego2010b}';
cdmax=2.9541;tcdmax=3.9364;clmax=0.47913;tclmax=5.6928;dpp=-0.11162;
fprintf(fid,'%s & $%.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ & $ %.4f $ \\\\ \\hline \n',refName,cdmax,tcdmax,clmax,tclmax,dpp);

refName='Sch\"afer {\em et al.}  \cite{SchaferEtal96}';
cdmaxL=2.93;cdmaxU=2.97;clmaxL=0.47;clmaxU=0.49;dppL=-0.1150;dppU=-0.1050;
fprintf(fid,'%s & $[%.3f,%.3f] $ &   & $ [%.3f,%.3f] $ &   & $[%.3f,%.3f] $ \\\\ \\hline \n',refName,cdmaxL,cdmaxU,clmaxL,clmaxU,dppL,dppU);



fprintf(fid,'\\end{tabular}\n');

fprintf(fid,'\\caption{Drag Lift and $\\Delta p(8)$} \n');
fprintf(fid,'\\end{center}\n');
fprintf(fid,'\\end{figure}\n');

fclose(fid);
